[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --workspace-root"]

[phases.build]
cmds = ["pnpm run build"]
env = [
  "DATABASE_URL",
  "POSTGRES_URL",
  "AUTH_SECRET",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN"
]

[start]
cmd = "pnpm run start"
