[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]
cacheDirs = [".next/cache", "node_modules/.cache"]  # << הוספתי שורה שמבטלת את ברירת המחדל הבעייתית
env = [
  "DATABASE_URL",
  "POSTGRES_URL",
  "AUTH_SECRET",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN"
]

[start]
cmd = "pnpm run start"
