[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "rm -f tsconfig.tsbuildinfo",
  "NODE_ENV=production pnpm run build:production"
]
cacheDirs = [
  ".next/cache",
  "node_modules/.cache"
]
env = [
  "NODE_ENV=production",
  "DATABASE_URL",
  "POSTGRES_URL",
  "AUTH_SECRET",
  "AUTH_TRUST_HOST",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "GOOGLE_APPLICATION_CREDENTIALS",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "KV_REST_API_TOKEN",
  "BYPASS_FIREBASE_AUTH"
]

[start]
cmd = "pnpm run start"
